version: '3.8'

services:
  smart_parking_db:
    image: mysql:8.0
    container_name: smart_parking_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: smart_parking
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  smart_parking_app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: smart_parking_app
    depends_on:
      - smart_parking_db
    volumes:
      - ../src/main/resources/hibernate.docker.cfg.xml:/app/src/main/resources/hibernate.cfg.xml
    # On force l'utilisation du fichier de config monté dans le répertoire de travail

volumes:
  db_data:
